# Generated by Django 3.1.12 on 2023-02-25 22:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=122)),
                ('header', models.CharField(max_length=122)),
                ('desc', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.TextField(default='')),
                ('state', models.TextField(default='')),
                ('tag', models.CharField(default='', max_length=122)),
                ('featured_package_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('eventdate', models.IntegerField(default=1)),
                ('eventday', models.TextField(default='')),
                ('eventmonth', models.TextField(default='')),
                ('eventyear', models.IntegerField(default=2020)),
                ('organizer', models.CharField(default='', max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Weddingbooking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_booked', models.DateTimeField(auto_now_add=True)),
                ('featured_package_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.customer')),
                ('service_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.servicepage')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.servicetype'),
        ),
    ]
