# Generated by Django 3.1.12 on 2023-02-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230225_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='tag',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='tag',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
