# Generated by Django 3.1.12 on 2023-02-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230225_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='eventdate',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='eventday',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='eventmonth',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='eventyear',
        ),
    ]
