# Generated by Django 3.1.12 on 2023-02-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20230225_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='city',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
