# Generated by Django 4.1.7 on 2023-02-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_auto_20230225_2339"),
    ]

    operations = [
        migrations.AddField(
            model_name="weddingbooking",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
